import { test } from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import { OAuth2Client, LoginTicket } from 'google-auth-library';
import { randomUUID } from 'node:crypto';
import { createAuth } from './auth.js';
import { createApp } from './app.js';
import { config } from './config.js';
import { pool } from './db.js';
import { createServer } from 'node:http';
import { attachChat } from './chat.js';
import { io as connectSocket, type Socket } from 'socket.io-client';

test('OAuth session lifecycle, rejection, persistence and CSRF with PostgreSQL', async () => {
  const subject = `test-${randomUUID()}`;
  let identity = subject;
  const settings = { ...config, clientId: 'test', clientSecret: 'test', production: false, appOrigin: 'http://127.0.0.1', callbackUrl: 'http://127.0.0.1/api/auth/google/callback' };
  let nonce = '';
  let state = '';
  let campus = true;
  const fake = new OAuth2Client();
  fake.generateAuthUrl = options => { nonce = String(options?.nonce); state = String(options?.state); return 'https://accounts.google.com/test'; };
  fake.getToken = (async () => ({ tokens: { id_token: 'test' } })) as typeof fake.getToken;
  fake.verifyIdToken = (async () => new LoginTicket('', { iss: 'https://accounts.google.com', aud: 'test', iat: 0, exp: 9999999999, sub: identity, nonce, email_verified: true, email: `${identity}@${campus ? 'vitbhopal.ac.in' : 'gmail.com'}`, hd: campus ? 'vitbhopal.ac.in' : undefined })) as typeof fake.verifyIdToken;
  const auth = createAuth(pool, settings, fake);
  const app = createApp(async () => {}, auth);
  const httpServer = createServer(app);
  const liveServer = attachChat(httpServer, auth.sessionMiddleware, pool, settings.appOrigin);
  await new Promise<void>(resolve => httpServer.listen(0, '127.0.0.1', resolve));
  const address = httpServer.address() as { port: number };
  const sockets: Socket[] = [];
  async function live(cookie: string) {
    const socket = connectSocket(`http://127.0.0.1:${address.port}`, { transports: ['websocket'], extraHeaders: { Origin: settings.appOrigin, Cookie: cookie.split(';')[0] }, reconnection: false });
    sockets.push(socket);
    await new Promise<void>((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('Socket connection timed out')), 5000);
      socket.once('connect', () => { clearTimeout(timer); resolve(); });
      socket.once('connect_error', error => { clearTimeout(timer); reject(error); });
    });
    return socket;
  }
  const agent = request.agent(app);
  let sessionId: string | undefined;
  try {
    assert.equal((await agent.get('/api/me')).status, 401);
    await agent.get('/api/auth/google').expect(302);
    const invalid = await agent.get('/api/auth/google/callback?code=test&state=wrong');
    assert.match(invalid.headers.location, /authError=state/);
    await agent.get('/api/auth/google').expect(302);
    campus = false;
    const rejected = await agent.get('/api/auth/google/callback').query({ code: 'test', state });
    assert.match(rejected.headers.location, /authError=campus/);
    assert.equal((await agent.get('/api/me')).status, 401);
    campus = true;
    await agent.get('/api/auth/google').expect(302);
    const loggedIn = await agent.get('/api/auth/google/callback').query({ code: 'test', state });
    assert.equal(loggedIn.headers.location, 'http://127.0.0.1/');
    const cookie = loggedIn.headers['set-cookie'][0];
    assert.match(cookie, /HttpOnly/); assert.match(cookie, /SameSite=Lax/);
    const me = await agent.get('/api/me').expect(200);
    await request(app).get('/api/me/profile').expect(401);
    await agent.patch('/api/me/profile').send({ display_name: 'No CSRF' }).expect(403);
    const patch = (body: object) => agent.patch('/api/me/profile').set('Origin', settings.appOrigin).set('x-csrf-token', me.body.csrfToken).send(body);
    await patch({ display_name: '  ' }).expect(400);
    await patch({ interests: ['Coding', 'Coding'] }).expect(400);
    await patch({ interests: ['Unknown'] }).expect(400);
    await patch({ bio: 'a'.repeat(501) }).expect(400);
    await patch({ id: randomUUID(), display_name: 'Other user' }).expect(400);
    const updated = await patch({ display_name: 'Campus Tester', bio: 'Hello campus!', interests: ['Coding', 'Music'] }).expect(200);
    assert.ok(updated.body.profile.profile_completed_at);
    assert.deepEqual(updated.body.profile.interests, ['Coding', 'Music']);
    const persisted = await agent.get('/api/me/profile').expect(200);
    assert.equal(persisted.body.profile.display_name, 'Campus Tester');
    const publicView = await agent.get(`/api/users/${me.body.user.id}`).expect(200);
    assert.deepEqual(Object.keys(publicView.body.profile).sort(), ['bio', 'display_name', 'id', 'interests']);
    await agent.patch(`/api/users/${me.body.user.id}`).send({ bio: 'no' }).expect(404);
    await request(app).get(`/api/users/${me.body.user.id}`).expect(401);
    await agent.get('/api/users/invalid').expect(400);
    await agent.get(`/api/users/${randomUUID()}`).expect(404);
    await patch({ bio: '' }).expect(200);
    const partial = await agent.get('/api/me/profile').expect(200);
    assert.deepEqual(partial.body.profile.interests, ['Coding', 'Music']);
    const payload = { title: 'Test campus plan', description: 'A test activity', category: 'Study', location: 'Library', starts_at: new Date(Date.now() + 86400000).toISOString(), ends_at: new Date(Date.now() + 90000000).toISOString(), capacity: 4 };
    const create = (body: object) => agent.post('/api/activities').set('Origin', settings.appOrigin).set('x-csrf-token', me.body.csrfToken).send(body);
    await request(app).get('/api/activities').expect(401);
    await agent.post('/api/activities').send(payload).expect(403);
    await create({ ...payload, capacity: 0 }).expect(400);
    await create({ ...payload, title: ' ' }).expect(400);
    await create({ ...payload, starts_at: new Date(0).toISOString() }).expect(400);
    await create({ ...payload, ends_at: payload.starts_at }).expect(400);
    await create({ ...payload, creator_id: randomUUID() }).expect(400);
    const created = await create(payload).expect(201);
    const activityId = created.body.activity.id;
    const detail = await agent.get(`/api/activities/${activityId}`).expect(200);
    assert.equal(detail.body.activity.participant_count, 1);
    const edit = (body: object) => agent.patch(`/api/activities/${activityId}`).set('Origin', settings.appOrigin).set('x-csrf-token', me.body.csrfToken).send(body);
    await edit({ title: 'Updated plan' }).expect(200);
    const feed = await agent.get('/api/activities?category=Study&limit=50').expect(200);
    assert.ok(feed.body.activities.some((a: { id: string }) => a.id === activityId));
    await agent.get('/api/activities?date=2026-02-30').expect(400);
    await agent.get('/api/activities?limit=-1').expect(400);
    await agent.get('/api/activities/bad-id').expect(400);
    identity = `${subject}-other`;
    const other = request.agent(app);
    await other.get('/api/auth/google').expect(302);
    const otherLogin = await other.get('/api/auth/google/callback').query({ code: 'test', state }).expect(302);
    const otherMe = await other.get('/api/me').expect(200);
    await other.get(`/api/activities/${activityId}`).expect(200);
    await other.patch(`/api/activities/${activityId}`).set('Origin', settings.appOrigin).set('x-csrf-token', otherMe.body.csrfToken).send({ title: 'Hijacked' }).expect(403);
    await other.post(`/api/activities/${activityId}/cancel`).set('Origin', settings.appOrigin).set('x-csrf-token', otherMe.body.csrfToken).expect(403);
    const join = () => other.post(`/api/activities/${activityId}/join`).set('Origin', settings.appOrigin).set('x-csrf-token', otherMe.body.csrfToken);
    const leave = () => other.delete(`/api/activities/${activityId}/participants/me`).set('Origin', settings.appOrigin).set('x-csrf-token', otherMe.body.csrfToken);
    const send = (body: unknown) => agent.post(`/api/activities/${activityId}/messages`).set('Origin', settings.appOrigin).set('x-csrf-token', me.body.csrfToken).send({ body });
    await request(app).get(`/api/activities/${activityId}/messages`).expect(401);
    await other.get(`/api/activities/${activityId}/messages`).expect(403);
    await other.post(`/api/activities/${activityId}/messages`).set('Origin', settings.appOrigin).set('x-csrf-token', otherMe.body.csrfToken).send({ body: 'Forbidden' }).expect(403);
    await join().expect(403);
    await other.patch('/api/me/profile').set('Origin', settings.appOrigin).set('x-csrf-token', otherMe.body.csrfToken).send({ display_name: 'Other student' }).expect(200);
    await request(app).post(`/api/activities/${activityId}/join`).expect(401);
    await other.post(`/api/activities/${activityId}/join`).expect(403);
    await agent.delete(`/api/activities/${activityId}/participants/me`).set('Origin', settings.appOrigin).set('x-csrf-token', me.body.csrfToken).expect(409);
    await join().expect(201);
    const otherSocket = await live(otherLogin.headers['set-cookie'][0]);
    const watched = await otherSocket.timeout(5000).emitWithAck('watch', activityId);
    assert.equal(watched.ok, true);
    await send(' ').expect(400);
    await send('x'.repeat(2001)).expect(400);
    await agent.post(`/api/activities/${activityId}/messages`).send({ body: 'No CSRF' }).expect(403);
    const notification = new Promise<void>((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('No live chat update received')), 5000);
      otherSocket.once('messages-changed', (...args) => { clearTimeout(timer); assert.equal(args.length, 0); resolve(); });
    });
    const sent = await send('<script>hello</script>').expect(201);
    await notification;
    const history = await other.get(`/api/activities/${activityId}/messages`).expect(200);
    assert.equal(history.body.messages[0].id, sent.body.message.id);
    assert.equal(history.body.messages[0].body, '<script>hello</script>');
    const restoredChat = await request(createApp(async () => {}, auth)).get(`/api/activities/${activityId}/messages`).set('Cookie', cookie.split(';')[0]).expect(200);
    assert.equal(restoredChat.body.messages.length, 1);
    await pool.query("INSERT INTO activity_messages (activity_id,user_id,body) SELECT $1,$2,'History ' || n FROM generate_series(1,52) n", [activityId, me.body.user.id]);
    const latest = await agent.get(`/api/activities/${activityId}/messages`).expect(200);
    assert.equal(latest.body.messages.length, 50); assert.equal(latest.body.hasMore, true);
    const older = await agent.get(`/api/activities/${activityId}/messages`).query({ before: latest.body.messages[0].id }).expect(200);
    assert.equal(older.body.messages.length, 3); assert.equal(older.body.hasMore, false);
    const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=', 'base64');
    const upload = (file: Buffer, name: string) => agent.post(`/api/activities/${activityId}/attachments`).set('Origin', settings.appOrigin).set('x-csrf-token', me.body.csrfToken).attach('file', file, name);
    const photo = await upload(png, 'photo.png').field('body', 'Our meeting spot').expect(201);
    const attachmentUrl = `/api/attachments/${photo.body.attachmentId}`;
    await request(app).get(attachmentUrl).expect(401);
    const fetched = await other.get(attachmentUrl).expect(200).expect('Content-Type', /image\/png/).expect('Cache-Control', 'private, no-store');
    assert.deepEqual(fetched.body, png);
    const mediaHistory = await agent.get(`/api/activities/${activityId}/messages`).expect(200);
    assert.equal(mediaHistory.body.messages.at(-1).attachment.id, photo.body.attachmentId);
    await upload(Buffer.from('<script>not an image</script>'), 'fake.png').expect(400);
    await upload(Buffer.concat([png, Buffer.alloc(10 * 1024 * 1024)]), 'too-large.png').expect(400);
    // Minimal ISO base media header exercises type detection and HTTP byte serving.
    const mp4 = Buffer.concat([Buffer.from([0,0,0,24]), Buffer.from('ftypisom'), Buffer.from([0,0,0,0]), Buffer.from('isommp42')]);
    const video = await upload(mp4, 'clip.mp4').expect(201);
    await other.get(`/api/attachments/${video.body.attachmentId}`).set('Range', 'bytes=0-7').expect(206).expect('Content-Range', 'bytes 0-7/24').expect('Content-Length', '8');
    await other.get(attachmentUrl).set('Range', 'bytes=999999-').expect(416);
    await agent.post(`/api/activities/${activityId}/attachments`).attach('file', png, 'photo.png').expect(403);
    await join().expect(409);
    const people = await other.get(`/api/activities/${activityId}/participants`).expect(200);
    assert.equal(people.body.participants.length, 2);
    assert.deepEqual(Object.keys(people.body.participants[0]).sort(), ['display_name', 'id', 'joined_at']);
    await other.delete(`/api/activities/${activityId}/participants/me`).expect(403);
    await leave().expect(200);
    await other.get(`/api/activities/${activityId}/messages`).expect(403);
    await other.get(attachmentUrl).expect(404);
    await other.post(`/api/activities/${activityId}/attachments`).set('Origin', settings.appOrigin).set('x-csrf-token', otherMe.body.csrfToken).attach('file', png, 'photo.png').expect(403);
    await other.post(`/api/activities/${activityId}/messages`).set('Origin', settings.appOrigin).set('x-csrf-token', otherMe.body.csrfToken).send({ body: 'Left activity' }).expect(403);
    otherSocket.disconnect();
    const revokedSocket = await live(otherLogin.headers['set-cookie'][0]);
    assert.equal((await revokedSocket.timeout(5000).emitWithAck('watch', activityId)).ok, false);
    revokedSocket.disconnect();
    await leave().expect(409);
    await edit({ capacity: 2 }).expect(200);
    identity = `${subject}-third`;
    const third = request.agent(app);
    await third.get('/api/auth/google').expect(302);
    await third.get('/api/auth/google/callback').query({ code: 'test', state }).expect(302);
    const thirdMe = await third.get('/api/me').expect(200);
    await third.patch('/api/me/profile').set('Origin', settings.appOrigin).set('x-csrf-token', thirdMe.body.csrfToken).send({ display_name: 'Third student' }).expect(200);
    const joinThird = () => third.post(`/api/activities/${activityId}/join`).set('Origin', settings.appOrigin).set('x-csrf-token', thirdMe.body.csrfToken);
    const race = await Promise.all([join(), joinThird()]);
    assert.deepEqual(race.map(response => response.status).sort(), [201, 409]);
    const full = await agent.get(`/api/activities/${activityId}/participants`).expect(200);
    assert.equal(full.body.participants.length, 2);
    if (race[0].status === 201) {
      await leave().expect(200); await joinThird().expect(201);
    } else {
      await third.delete(`/api/activities/${activityId}/participants/me`).set('Origin', settings.appOrigin).set('x-csrf-token', thirdMe.body.csrfToken).expect(200);
      await join().expect(201);
    }
    await edit({ capacity: 1 }).expect(409);
    await agent.post(`/api/activities/${activityId}/cancel`).set('Origin', settings.appOrigin).set('x-csrf-token', me.body.csrfToken).expect(200);
    const canceled = await agent.get(`/api/activities/${activityId}`).expect(200);
    assert.ok(canceled.body.activity.canceled_at);
    await send('After cancellation').expect(409);
    const readOnly = await agent.get(`/api/activities/${activityId}/messages`).expect(200);
    assert.equal(readOnly.body.readOnly, true);
    const afterCancel = await agent.get('/api/activities?category=Study&limit=50').expect(200);
    assert.equal(afterCancel.body.activities.some((a: { id: string }) => a.id === activityId), false);
    await edit({ title: 'Revive' }).expect(409);
    await join().expect(409);
    await third.post('/api/logout').set('Origin', settings.appOrigin).set('x-csrf-token', thirdMe.body.csrfToken).expect(204);
    await other.post('/api/logout').set('Origin', settings.appOrigin).set('x-csrf-token', otherMe.body.csrfToken).expect(204);
    const stored = await pool.query("SELECT sid FROM sessions WHERE sess->>'userId' = $1", [me.body.user.id]);
    sessionId = stored.rows[0]?.sid;
    assert.ok(sessionId);
    // A fresh Express instance can load the same PostgreSQL session.
    await request(createApp(async () => {}, auth)).get('/api/me').set('Cookie', cookie.split(';')[0]).expect(200);
    const restored = await request(createApp(async () => {}, auth)).get('/api/me/profile').set('Cookie', cookie.split(';')[0]).expect(200);
    assert.equal(restored.body.profile.display_name, 'Campus Tester');
    await agent.post('/api/logout').set('Origin', settings.appOrigin).expect(403);
    await agent.post('/api/logout').set('Origin', 'https://evil.example').set('x-csrf-token', me.body.csrfToken).expect(403);
    await agent.post('/api/logout').set('Origin', settings.appOrigin).set('x-csrf-token', me.body.csrfToken).expect(204);
    await agent.get('/api/me').expect(401);
    await agent.get('/api/auth/google/callback').query({ code: 'test', state }).expect(302).expect('Location', /authError=state/);
  } finally {
    for (const socket of sockets) socket.disconnect();
    await new Promise<void>(resolve => liveServer.close(() => resolve()));
    if (sessionId) await pool.query('DELETE FROM sessions WHERE sid = $1', [sessionId]);
    await pool.query('DELETE FROM activities WHERE creator_id IN (SELECT id FROM users WHERE google_id = ANY($1::text[]))', [[subject, `${subject}-other`, `${subject}-third`]]);
    await pool.query('DELETE FROM users WHERE google_id = ANY($1::text[])', [[subject, `${subject}-other`, `${subject}-third`]]);
    await pool.end();
  }
});
