import { ActivityFeed, ActivityPage } from './Activities';
import { PublicProfile } from './Profile';
import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes } from 'react-router-dom';
import { ArrowUpRight, Check, Circle, Coffee, Compass, Database, Layers, RefreshCw, Sparkles, Users } from 'lucide-react';
import './style.css';
import { AuthPanel } from './AuthPanel';
function Setup() {
  const [status, setStatus] = useState<'loading' | 'connected' | 'unavailable' | 'offline'>('loading');
  const [attempt, setAttempt] = useState(0);
  useEffect(() => {
    const controller = new AbortController();
    setStatus('loading');
    fetch('/api/health', { signal: controller.signal }).then(async response => {
      const body = await response.json();
      setStatus(response.ok && body.ok === true ? 'connected' : 'unavailable');
    }).catch(() => { if (!controller.signal.aborted) setStatus('offline'); });
    return () => controller.abort();
  }, [attempt]);
  const ready = status === 'connected';
  return <><header><Link className="brand" to="/"><span className="brand-icon"><Users size={23}/></span>huddle<span className="brand-dot">.</span></Link><span className="badge">THE CAMPUS CONNECTION</span><a href="#setup" className="header-link">Build workspace <ArrowUpRight size={16}/></a></header>
  <main><div className="eyebrow"><span/> SMALL PLANS. GREAT COMPANY.</div><section className="hero"><div><h1>Your people.<br/>Your campus.<br/><em>Your next thing.</em></h1><p>From a quick coffee to a weekend game.<br/>Make room for the moments that bring you together.</p><a className="button" href="#setup">Let’s build Huddle <ArrowUpRight size={18}/></a><div className="hero-note"><span className="mini-avatars">A<span>M</span><span>R</span></span>Made for a campus full of possibilities.</div></div><div className="art" aria-label="Illustration of campus activities"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="art-caption">GOOD THINGS START WITH A HELLO</span><div className="activity-card coffee"><div className="tile"><Coffee/></div><small>THE LITTLE PLANS</small><h3>Coffee & conversation</h3><p>A new face. A familiar spot.</p><span className="card-tag">Find your kind of people ↗</span></div><div className="activity-card together"><div className="tile"><Users/></div><h3>Better together.</h3><p>On campus. In real life.</p><div className="color-dots"><i/><i/><i/><i/></div></div><span className="spark"><Sparkles size={36}/></span><span className="art-footer">A little less scrolling. A little more showing up.</span></div></section>
  <AuthPanel/><ActivityFeed/><section id="setup" className="setup"><div className="section-heading"><div><span className="eyebrow">01 / THE FOUNDATION</span><h2>Something good is taking shape.</h2></div><span className="pill">Development workspace</span></div><div className="setup-grid"><article className="connection"><div className="card-heading"><Database size={22}/><span>Local environment</span><span className={`status-dot ${ready ? 'ready' : ''}`}/></div><h3>{status === 'loading' ? 'Checking your connection…' : ready ? 'You’re connected.' : status === 'offline' ? 'Let’s start the API.' : 'Let’s connect the database.'}</h3><p role="status">{ready ? 'The API can reach PostgreSQL. Your foundation is ready for the next milestone.' : status === 'loading' ? 'Contacting the API and PostgreSQL.' : status === 'offline' ? 'The API is not responding. Start both services with npm.cmd run dev.' : 'The API is running. Start PostgreSQL, then apply the migration to finish setup.'}</p><code>docker compose up -d<br/>npm.cmd run db:migrate</code><button onClick={() => setAttempt(n => n + 1)} disabled={status === 'loading'}><RefreshCw size={15}/> Check connection</button></article><article className="roadmap"><div className="card-heading"><Layers size={22}/><span>The path to your first Huddle</span></div>{[[true, 'App foundation', 'React, Express, and a PostgreSQL-ready schema'], [true, 'Campus sign-in', 'Verified student access and secure sessions'], [false, 'Profiles & activities', 'Introduce yourself. Find something to do.'], [false, 'Join & chat', 'Turn a shared interest into a real connection']].map(([done, title, detail]) => <div className="step" key={String(title)}><span className={done ? 'step-icon done' : 'step-icon'}>{done ? <Check size={15}/> : <Circle size={12}/>}</span><div><strong>{title}</strong><p>{detail}</p></div>{done && <small>BUILT</small>}</div>)}</article></div></section><div className="closing"><Compass size={19}/><p>One campus. Countless ways to belong.</p><span>Built one meaningful connection at a time.</span></div></main><footer><span>huddle. <span>Your campus, together.</span></span><span>Foundation / v0.1</span></footer></>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><Routes><Route path="/activities/new" element={<ActivityPage mode="new"/>}/><Route path="/activities/:id/edit" element={<ActivityPage mode="edit"/>}/><Route path="/activities/:id" element={<ActivityPage mode="detail"/>}/><Route path="/users/:id" element={<PublicProfile/>}/><Route path="/" element={<Setup/>}/><Route path="*" element={<main><h1>Page not found.</h1><Link to="/">Back to Huddle</Link></main>}/></Routes></BrowserRouter></React.StrictMode>);
